import { Component, OnInit } from '@angular/core';
import { ItemQuery } from './state/item.query';
import { Observable } from 'rxjs';
import { Item } from './state/item.model';
import { ItemStore } from './state/item.store';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  items$: Observable<Item[]> | undefined;
  constructor(private itemQuery: ItemQuery, private itemStore: ItemStore) {
    const initialItem: Item = {
      id: 1, // Replace with a unique ID (e.g., generated by a service or database)
      name: 'Initial Item',
    };
    this.itemStore.addItems([initialItem]);
  }

  ngOnInit() {
    this.items$ = this.itemQuery.items$;
  }
}
